CREATE TABLE GT_Account
(
	UniqueID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	AccountID NVARCHAR(16) NOT NULL,
	Password NVARCHAR(50) NOT NULL,
	RegisterTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

#INSERT INTO GT_Account( AccountID, Password ) VALUES( 'test, '1234' );

CREATE TABLE GT_Player
(
	AccountID INTEGER NOT NULL,
	PlayerID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	NickName NVARCHAR(50) NOT NULL,
	LoginTime TIMESTAMP NULL
);

#INSERT INTO GT_Player( AccountID, NickName ) VALUES( 1, '하악하악' );